const fs = require('fs');
const path = require('path');
const { getCurrentUTCDateTime, getDateFormatted } = require('../utils/dateUtils');
const { ensureDirectoryExists } = require('../utils/fileUtils');

function generateMangleConfigs(startNumber, count) {
    let contents = [];
    
    contents.push(`# Generated on: ${getCurrentUTCDateTime()}`);
    contents.push(`# Generated by: krystallix`);
    contents.push('');
    contents.push('/ip firewall mangle');

    for (let i = 0; i < count; i++) {
        const currentNumber = startNumber + i;
        contents.push(`add action=mark-routing chain=prerouting dst-address-list=!bogon \\\
    new-routing-mark=VPN-${currentNumber} passthrough=no src-address-list=mangle-${currentNumber}`);
    }

    return contents.join('\n');
}

function handleMangleGeneration(readline, OUTPUT_PATH, showMainMenu) {
    readline.question('Enter starting number: ', (startNum) => {
        readline.question('Enter how many configurations to generate: ', (count) => {
            try {
                ensureDirectoryExists(OUTPUT_PATH);
                const fileName = `mangle-firewall-${getDateFormatted()}.txt`;
                const fullPath = path.join(OUTPUT_PATH, fileName);

                const content = generateMangleConfigs(parseInt(startNum), parseInt(count));
                fs.writeFileSync(fullPath, content);

                console.log(`\nSuccess! File generated: ${fullPath}`);
                console.log(`Generated ${count} Mangle rules starting from VPN-${startNum}`);
            } catch (error) {
                console.error('Error:', error.message);
            }
            showMainMenu();
        });
    });
}

module.exports = {
    generateMangleConfigs,
    handleMangleGeneration
};