const fs = require('fs');
const path = require('path');
const { getCurrentUTCDateTime, getDateFormatted } = require('../utils/dateUtils');
const { ensureDirectoryExists } = require('../utils/fileUtils');

function generateRouteConfigs(startNumber, count) {
    let contents = [];
    
    contents.push(`# Generated on: ${getCurrentUTCDateTime()}`);
    contents.push(`# Generated by: krystallix`);
    contents.push('');
    contents.push('/ip route');

    for (let i = 0; i < count; i++) {
        const currentNumber = startNumber + i;
        contents.push(`add gateway=VPN-${currentNumber} routing-table=VPN-${currentNumber}`);
    }
    return contents.join('\n');
}

function handleRouteGeneration(rl, OUTPUT_PATH, showMainMenu) {
    rl.question('Enter starting VPN number: ', (startNum) => {
        rl.question('Enter total VPN configurations: ', (count) => {
            try {
                ensureDirectoryExists(OUTPUT_PATH);
                const fileName = `routes-${getDateFormatted()}.txt`;
                const fullPath = path.join(OUTPUT_PATH, fileName);

                const content = generateRouteConfigs(parseInt(startNum), parseInt(count));
                fs.writeFileSync(fullPath, content);

                console.log(`\nSuccess! File generated: ${fullPath}`);
                console.log(`Generated ${count} Route configurations starting from VPN-${startNum}`);
            } catch (error) {
                console.error('Error generating file:', error);
            }
            showMainMenu();
        });
    });
}

module.exports = {
    generateRouteConfigs,
    handleRouteGeneration
};