const fs = require('fs');
const path = require('path');
const { getCurrentUTCDateTime, getDateFormatted } = require('../utils/dateUtils');
const { ensureDirectoryExists } = require('../utils/fileUtils');

function generateRouteTableConfigs(startNumber, count) {
    let contents = [];
    
    contents.push(`# Generated on: ${getCurrentUTCDateTime()}`);
    contents.push(`# Generated by: krystallix`);
    contents.push('');
    contents.push('/routing table');

    for (let i = 0; i < count; i++) {
        const currentNumber = startNumber + i;
        contents.push(`add fib name=VPN-${currentNumber}`);
    }
    return contents.join('\n');
}

function handleRouteTableGeneration(rl, OUTPUT_PATH, showMainMenu) {
    rl.question('Enter starting number: ', (startNum) => {
        rl.question('Enter how many configurations to generate: ', (count) => {
            try {
                ensureDirectoryExists(OUTPUT_PATH);
                const fileName = `route-table-${getDateFormatted()}.txt`;
                const fullPath = path.join(OUTPUT_PATH, fileName);

                const content = generateRouteTableConfigs(parseInt(startNum), parseInt(count));
                fs.writeFileSync(fullPath, content);

                console.log(`\nSuccess! File generated: ${fullPath}`);
                console.log(`Generated ${count} Route Table configurations starting from VPN-${startNum}`);
            } catch (error) {
                console.error('Error generating file:', error);
            }
            showMainMenu();
        });
    });
}

module.exports = {
    generateRouteTableConfigs,
    handleRouteTableGeneration
};